# Generated by Django 2.2 on 2022-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stewarts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawngallons', models.IntegerField()),
                ('lawnsquarefootage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PestCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestgallons', models.IntegerField()),
                ('pestsquarefootage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreeCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treegallons', models.IntegerField()),
                ('treesquarefootage', models.IntegerField()),
            ],
        ),
    ]
