# Generated by Django 2.2 on 2022-04-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stewarts', '0002_lawncalc_pestcalc_treecalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('advice', models.CharField(max_length=5500)),
            ],
        ),
    ]
